# Generated by Django 3.2 on 2021-04-14 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fuelType', models.CharField(choices=[('Gas', 'Gas'), ('Diesel', 'Diesel'), ('Electric', 'Electric')], max_length=50)),
                ('fuelLevel', models.IntegerField()),
            ],
        ),
    ]
