# Generated by Django 3.2 on 2021-04-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='imageUrl',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='robot',
            name='fuelLevel',
            field=models.IntegerField(default=100),
        ),
    ]
